// GENERADO por tools/ayuda-sismo/build_municipios_js.py — no editar a mano.
//
// [clave sin tildes, nombre, departamento, en_zona_afectada]. Ordenado de más
// largo a más corto para que "San Jose del Palmar" gane sobre un fragmento suyo.
//
// ⚠️ en_zona_afectada = 0 son ciudades que se vigilan solo para poder
// detectarlas en un titular (Bogotá, Medellín, Barranquilla…). NO deben entrar
// al conteo de "municipios sin cobertura": no estaban en la zona del sismo y
// listarlas ahí infla el hallazgo principal de la página.
//
// 24 municipios quedaron FUERA por nombre ambiguo o muy corto: su
// nombre casa con países, estados de EE. UU., departamentos o palabras
// comunes, y detectarlos por texto inflaría el conteo con notas ajenas.
// La página lo declara en la metodología.
export const MUNICIPIOS = [
  ["el canton del san pablo", "El Cantón del San Pablo", "Chocó", 1],
  ["el litoral del san juan", "El Litoral del San Juan", "Chocó", 1],
  ["nuevo belen de bajira", "Nuevo Belén de Bajirá", "Chocó", 1],
  ["san jose del palmar", "San José del Palmar", "Chocó", 1],
  ["santa rosa de cabal", "Santa Rosa de Cabal", "Risaralda", 1],
  ["union panamericana", "Unión Panamericana", "Chocó", 1],
  ["carmen del darien", "Carmen del Darién", "Chocó", 1],
  ["belen de umbria", "Belén de Umbría", "Risaralda", 1],
  ["medio san juan", "Medio San Juan", "Chocó", 1],
  ["ansermanuevo", "Ansermanuevo", "Valle del Cauca", 1],
  ["bahia solano", "Bahía Solano", "Chocó", 1],
  ["barranquilla", "Barranquilla", "Atlántico", 0],
  ["bogota. d.c.", "Bogotá D.C.", "Bogotá D.C.", 0],
  ["buenaventura", "Buenaventura", "Valle del Cauca", 1],
  ["bugalagrande", "Bugalagrande", "Valle del Cauca", 1],
  ["dosquebradas", "Dosquebradas", "Risaralda", 1],
  ["medio atrato", "Medio Atrato", "Chocó", 1],
  ["puerto meluk", "Medio Baudó", "Chocó", 1],
  ["bucaramanga", "Bucaramanga", "Santander", 0],
  ["marquetalia", "Marquetalia", "Caldas", 1],
  ["medio baudo", "Medio Baudó", "Chocó", 1],
  ["pensilvania", "Pensilvania", "Caldas", 1],
  ["pie de pato", "Alto Baudó", "Chocó", 1],
  ["pueblo rico", "Pueblo Rico", "Risaralda", 1],
  ["alto baudo", "Alto Baudó", "Chocó", 1],
  ["bajo baudo", "Bajo Baudó", "Chocó", 1],
  ["belalcazar", "Belalcázar", "Caldas", 1],
  ["bellavista", "Bojayá", "Chocó", 1],
  ["bogota d c", "Bogotá D.C.", "Bogotá D.C.", 0],
  ["buenavista", "Buenavista", "Quindío", 1],
  ["caicedonia", "Caicedonia", "Valle del Cauca", 1],
  ["candelaria", "Candelaria", "Valle del Cauca", 1],
  ["el cerrito", "El Cerrito", "Valle del Cauca", 1],
  ["filadelfia", "Filadelfia", "Caldas", 1],
  ["la tebaida", "La Tebaida", "Quindío", 1],
  ["las animas", "Unión Panamericana", "Chocó", 1],
  ["manzanares", "Manzanares", "Caldas", 1],
  ["montenegro", "Montenegro", "Quindío", 1],
  ["roldanillo", "Roldanillo", "Valle del Cauca", 1],
  ["villamaria", "Villamaría", "Caldas", 1],
  ["andalucia", "Andalucía", "Valle del Cauca", 1],
  ["cartagena", "Cartagena", "Bolívar", 0],
  ["chinchina", "Chinchiná", "Caldas", 1],
  ["el carmen", "El Carmen", "Chocó", 1],
  ["la cumbre", "La Cumbre", "Valle del Cauca", 1],
  ["la dorada", "La Dorada", "Caldas", 1],
  ["manizales", "Manizales", "Caldas", 1],
  ["marulanda", "Marulanda", "Caldas", 1],
  ["rio quito", "Río Quito", "Chocó", 1],
  ["san pedro", "San Pedro", "Valle del Cauca", 1],
  ["santuario", "Santuario", "Risaralda", 1],
  ["aranzazu", "Aránzazu", "Caldas", 1],
  ["certegui", "Certeguí", "Chocó", 1],
  ["circasia", "Circasia", "Quindío", 1],
  ["el dovio", "El Dovio", "Valle del Cauca", 1],
  ["filandia", "Filandia", "Quindío", 1],
  ["marsella", "Marsella", "Risaralda", 1],
  ["medellin", "Medellín", "Antioquia", 0],
  ["mistrato", "Mistrató", "Risaralda", 1],
  ["norcasia", "Norcasia", "Caldas", 1],
  ["quimbaya", "Quimbaya", "Quindío", 1],
  ["quinchia", "Quinchía", "Risaralda", 1],
  ["riosucio", "Riosucio", "Caldas", 1],
  ["salamina", "Salamina", "Caldas", 1],
  ["trujillo", "Trujillo", "Valle del Cauca", 1],
  ["victoria", "Victoria", "Caldas", 1],
  ["aguadas", "Aguadas", "Caldas", 1],
  ["anserma", "Anserma", "Caldas", 1],
  ["armenia", "Armenia", "Quindío", 1],
  ["calarca", "Calarcá", "Quindío", 1],
  ["cartago", "Cartago", "Valle del Cauca", 1],
  ["condoto", "Condoto", "Chocó", 1],
  ["ginebra", "Ginebra", "Valle del Cauca", 1],
  ["guatica", "Guática", "Risaralda", 1],
  ["istmina", "Istmina", "Chocó", 1],
  ["jamundi", "Jamundí", "Valle del Cauca", 1],
  ["marmato", "Marmato", "Caldas", 1],
  ["paimado", "Río Quito", "Chocó", 1],
  ["palmira", "Palmira", "Valle del Cauca", 1],
  ["pereira", "Pereira", "Risaralda", 1],
  ["pizarro", "Bajo Baudó", "Chocó", 1],
  ["pradera", "Pradera", "Valle del Cauca", 1],
  ["rio iro", "Río Iró", "Chocó", 1],
  ["riofrio", "Riofrío", "Valle del Cauca", 1],
  ["viterbo", "Viterbo", "Caldas", 1],
  ["acandi", "Acandí", "Chocó", 1],
  ["alcala", "Alcalá", "Valle del Cauca", 1],
  ["atrato", "Atrato", "Chocó", 1],
  ["bagado", "Bagadó", "Chocó", 1],
  ["balboa", "Balboa", "Risaralda", 1],
  ["bogota", "Bogotá D.C.", "Bogotá D.C.", 0],
  ["bojaya", "Bojayá", "Chocó", 1],
  ["calima", "Calima", "Valle del Cauca", 1],
  ["darien", "Calima", "Valle del Cauca", 1],
  ["jurado", "Juradó", "Chocó", 1],
  ["novita", "Nóvita", "Chocó", 1],
  ["pacora", "Pácora", "Caldas", 1],
  ["quibdo", "Quibdó", "Chocó", 1],
  ["samana", "Samaná", "Caldas", 1],
  ["unguia", "Unguía", "Chocó", 1],
  ["yotoco", "Yotoco", "Valle del Cauca", 1],
  ["zarzal", "Zarzal", "Valle del Cauca", 1],
  ["dagua", "Dagua", "Valle del Cauca", 1],
  ["lloro", "Lloró", "Chocó", 1],
  ["mutis", "Bahía Solano", "Chocó", 1],
  ["neira", "Neira", "Caldas", 1],
  ["neiva", "Neiva", "Huila", 0],
  ["nuqui", "Nuquí", "Chocó", 1],
  ["pasto", "Pasto", "Nariño", 0],
  ["pijao", "Pijao", "Quindío", 1],
  ["tulua", "Tuluá", "Valle del Cauca", 1],
  ["ulloa", "Ulloa", "Valle del Cauca", 1],
  ["vijes", "Vijes", "Valle del Cauca", 1],
  ["yumbo", "Yumbo", "Valle del Cauca", 1],
  ["apia", "Apía", "Risaralda", 1],
  ["cali", "Cali", "Valle del Cauca", 1],
  ["sipi", "Sipí", "Chocó", 1],
  ["tado", "Tadó", "Chocó", 1]
];

export const MUNICIPIOS_EXCLUIDOS = ["argelia (Valle del Cauca)", "bolivar (Valle del Cauca)", "buga (Valle del Cauca)", "cordoba (Quindío)", "el aguila (Valle del Cauca)", "el cairo (Valle del Cauca)", "florida (Valle del Cauca)", "genova (Quindío)", "guacari (Valle del Cauca)", "la celia (Risaralda)", "la merced (Caldas)", "la union (Valle del Cauca)", "la victoria (Valle del Cauca)", "la virginia (Risaralda)", "obando (Valle del Cauca)", "palestina (Caldas)", "restrepo (Valle del Cauca)", "risaralda (Caldas)", "salento (Quindío)", "san jose (Caldas)", "sevilla (Valle del Cauca)", "supia (Caldas)", "toro (Valle del Cauca)", "versalles (Valle del Cauca)"];
