#!/usr/bin/env python3
"""
translate.py — Genera analisis-estrutural.html (PT-BR) a partir de
analisis-estructural.html (ES) aplicando un diccionario ordenado.

Estrategia:
- PHRASES = frases largas (≥ 8 chars) que se reemplazan como substring.
  Son inequívocas y no caen en false-positives.
- WORDS = palabras sueltas que se reemplazan SOLO con word-boundary
  (regex \b), para evitar romper substrings (e.g. "ritual" → "riseu").
- Protegemos <style> y <script> antes; en <script> traducimos sólo el
  contenido de string-literals que parezcan UI (≥4 chars + contiene
  espacios o tildes).
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# Mapa ES → PT de los 8 módulos del Lab. Se usa para (a) elegir el nombre de
# salida y (b) reescribir los cross-links entre módulos. La entrada
# analisis-estrutural.html conserva su nombre porque index.html ya la enlaza
# para los visitantes de Brasil; los demás usan sufijo -pt.
MODULES = {
    "analisis-estructural.html": "analisis-estrutural.html",
    "mactor.html":               "mactor-pt.html",
    "problema-publico.html":     "problema-publico-pt.html",
    "evaluacion.html":           "evaluacion-pt.html",
    "alternativas.html":         "alternativas-pt.html",
    "ain.html":                  "ain-pt.html",
    "prospect-escenarios.html":  "prospect-escenarios-pt.html",
    "comunicar.html":            "comunicar-pt.html",
}

# ─── PHRASES (≥8 chars, substring replace, orden manual) ──────────────────
PHRASES = [
    # Title / meta
    ("Lab de Políticas Públicas y Prospectiva · Ricardo.Ruiz",
     "Lab de Políticas Públicas e Prospectiva · Ricardo.Ruiz"),
    ("Lab integrado de políticas públicas y prospectiva: análisis estructural de sistemas, mapeo de actores y diseño de problemas públicos. Para planeación territorial, política sectorial y diagnóstico estratégico.",
     "Lab integrado de políticas públicas e prospectiva: análise estrutural de sistemas, mapeamento de atores e desenho de problemas públicos. Para planejamento territorial, política setorial e diagnóstico estratégico."),

    # Hub welcome / framing
    ("Política pública que aguanta en comité",
     "Política pública que se sustenta em comitê"),
    ("aguanta en comité",
     "se sustenta em comitê"),  # versión sin prefijo (tiene <em> alrededor)
    ("Política pública que",
     "Política pública que"),  # marca como traducido para evitar re-match
    ("aguanta", "aguenta"),
    ("aguante", "aguente"),
    ("Para diseñar política pública",
     "Para desenhar política pública"),
    ("Siete herramientas conectadas para equipos técnicos y consultoras que necesitan sustentar decisiones",
     "Sete ferramentas conectadas para equipes técnicas e consultorias que precisam sustentar decisões"),
    ("Una política pública — sea de seguridad, de educación, de movilidad,",
     "Uma política pública — seja de segurança, educação, mobilidade"),
    ("de salud — está hecha de muchas piezas que se influyen entre sí",
     "ou saúde — é feita de muitas peças que se influenciam mutuamente"),
    ("Cada uno de los cinco módulos está construido sobre las escuelas",
     "Cada um dos cinco módulos está construído sobre as escolas"),
    ("que la disciplina considera fundacionales — citadas por nombre",
     "que a disciplina considera fundadoras — citadas por nome"),
    ("La mayoría de consultorías repite la receta canónica genérica",
     "A maioria das consultorias repete a receita canônica genérica"),
    ("de los noventas. Este lab incorpora explícitamente investigaciones",
     "dos anos noventa. Este lab incorpora explicitamente pesquisas"),
    ("Las herramientas anglo (Theory Maker, Causal Map, DevResults, Logframer)",
     "As ferramentas anglo (Theory Maker, Causal Map, DevResults, Logframer)"),
    ("no hablan el idioma institucional latinoamericano. Este lab",
     "não falam a língua institucional latino-americana. Este lab"),

    # Wizard
    ("¿No sabes por dónde empezar? Te ayudamos a escoger según tu",
     "Não sabe por onde começar? Ajudamos você a escolher conforme sua"),
    ("organización, tu proceso y tu entregable esperado.",
     "organização, seu processo e o entregável esperado."),
    ("Ayúdame a escoger",
     "Ajude-me a escolher"),
    ("Hay módulos más útiles antes de tomar la decisión",
     "Há módulos mais úteis antes de tomar a decisão"),
    ("y otros más útiles cuando ya hay rumbo definido.",
     "e outros mais úteis quando já há um rumo definido."),

    # Stages
    ("Para entender un problema complejo lo primero es nombrar",
     "Para entender um problema complexo o primeiro é nomear"),
    ("las piezas que lo componen. Las llamamos",
     "as peças que o compõem. Chamamos-as de"),
    ("Las variables son las piezas con las que vas a describir",
     "As variáveis são as peças com as quais você vai descrever"),
    ("tu sistema. La calidad del análisis depende casi en su totalidad",
     "seu sistema. A qualidade da análise depende quase totalmente"),
    ("Edita, agrega o quita variables según tu caso. Recomendamos",
     "Edite, acrescente ou remova variáveis conforme seu caso. Recomendamos"),
    ("entre 10 y 25: menos pierde resolución, más vuelve pesada",
     "entre 10 e 25: menos perde resolução, mais torna pesada"),
    ("Por debajo de 8 el análisis",
     "Abaixo de 8 a análise"),
    ("pierde resolución; por encima de 30 la matriz se vuelve",
     "perde resolução; acima de 30 a matriz fica"),
    ("agotadora de llenar",
     "exaustiva de preencher"),
    ("Evita variables que se solapen.",
     "Evite variáveis que se sobreponham."),
    ("juntas confunden el análisis",
     "juntas confundem a análise"),

    # Capture / matrix
    ("También puedes navegar entre celdas con las flechas del teclado",
     "Você também pode navegar entre células com as setas do teclado"),
    ("escribir el número directamente, y usar la tecla",
     "digitar o número diretamente e usar a tecla"),
    ("para invertir el signo de la celda en foco.",
     "para inverter o sinal da célula em foco."),
    ("La diagonal está bloqueada porque una variable no se influye a sí misma.",
     "A diagonal está bloqueada porque uma variável não se influencia a si mesma."),
    ("La respuesta es nula, débil, media o fuerte (de 0 a 3)",
     "A resposta é nula, fraca, média ou forte (de 0 a 3)"),
    ("deliberadamente simple para que tu equipo pueda discutirla",
     "deliberadamente simples para que sua equipe possa discuti-la"),
    ("El umbral filtra qué relaciones cuentan como",
     "O limiar filtra quais relações contam como"),
    ("influye realmente sobre",
     "realmente influencia"),
    ("Sube si el sistema es muy denso.",
     "Aumente se o sistema for muito denso."),

    # Results
    ("Llegaste a la parte más importante. La herramienta tomó",
     "Você chegou à parte mais importante. A ferramenta pegou"),
    ("las calificaciones de tu matriz y aplicó",
     "as classificações da sua matriz e aplicou"),
    ("Cuando las tres técnicas coinciden en señalar una pieza como",
     "Quando as três técnicas coincidem em apontar uma peça como"),
    ("importante, la conclusión es robusta. Cuando difieren, ahí hay algo",
     "importante, a conclusão é robusta. Quando divergem, há aí algo"),
    ("para inyectarla al state pero requiere revisión humana antes de ir a comité",
     "para injetá-la no state, mas requer revisão humana antes de ir ao comitê"),
    ("La decisión final siempre se documenta con justificación humana",
     "A decisão final sempre é documentada com justificativa humana"),
    ("Tómate el tiempo que necesites — esto es lo único",
     "Reserve o tempo que precisar — isso é a única coisa"),
    ("que la herramienta no puede hacer por ti.",
     "que a ferramenta não pode fazer por você."),

    # Module summary cards (hub grid)
    ("Qué variables mueven el sistema. Identifica palancas, críticas",
     "Quais variáveis movem o sistema. Identifica alavancas, críticas"),
    ("y resultados con 3 lentes complementarias y bandas de incertidumbre",
     "e resultados com 3 lentes complementares e bandas de incerteza"),
    ("Quién apoya, quién bloquea, quién decide. Mapea influencia,",
     "Quem apoia, quem bloqueia, quem decide. Mapeia influência,"),
    ("dependencia y posiciones frente a objetivos clave.",
     "dependência e posições frente a objetivos-chave."),
    ("Enmarca el problema, construye alternativas y compáralas con",
     "Enquadra o problema, constrói alternativas e as compara com"),
    ("criterios explícitos. El paso 0 antes de cualquier matriz.",
     "critérios explícitos. O passo 0 antes de qualquer matriz."),
    ("Diseña el esquema de evaluación: pregunta evaluativa, teoría",
     "Desenha o esquema de avaliação: pergunta avaliativa, teoria"),
    ("de cambio, indicadores SMART, selector de método",
     "da mudança, indicadores SMART, seletor de método"),
    ("Construye alternativas con método: análisis morfológico de",
     "Constrói alternativas com método: análise morfológica de"),
    ("variables × opciones, robustez en cuatro escenarios y lente",
     "variáveis × opções, robustez em quatro cenários e lente"),
    ("Sustenta el proyecto normativo con AIN: problema regulatorio,",
     "Sustenta o projeto normativo com AIN: problema regulatório,"),
    ("objetivos medibles, opciones (statu quo · directo · sandbox ·",
     "objetivos mensuráveis, opções (statu quo · direto · sandbox ·"),
    ("Construye 4 futuros plausibles desde 2 incertidumbres críticas",
     "Constrói 4 futuros plausíveis a partir de 2 incertezas críticas"),
    ("y prueba tus variables/actores/alternativas contra cada uno.",
     "e testa suas variáveis/atores/alternativas contra cada um."),

    # MicMac / DEMATEL / ISM blocks
    ("ubica cada pieza en uno de cuatro cuadrantes",
     "posiciona cada peça em um dos quatro quadrantes"),
    ("según cuánto influye y cuánto depende del resto.",
     "segundo quanto influencia e quanto depende do restante."),
    ("Te da las palancas, los re",
     "Dá as alavancas, os re"),
    ("distingue causas de efectos: pone número a cuánto está cada pieza",
     "distingue causas de efeitos: coloca número em quanto cada peça está"),
    ("lanzando influencia sobre el resto",
     "emitindo influência sobre o restante"),
    ("recibiéndola",
     "recebendo-a"),
    ("organiza las piezas en niveles, como una pirámide,",
     "organiza as peças em níveis, como uma pirâmide,"),
    ("desde las que determinan el sistema",
     "desde as que determinam o sistema"),
    ("hasta las que solo cambian cuando el sistema entero cambia",
     "até as que só mudam quando o sistema inteiro muda"),
    ("organiza las piezas en una pirámide jerárquica.",
     "organiza as peças em uma pirâmide hierárquica."),
    ("Arriba quedan las que determinan el sistema; abajo, las que solo cambian",
     "Acima ficam as que determinam o sistema; abaixo, as que só mudam"),
    ("Usa la matriz de alcanzabilidad",
     "Usa a matriz de alcançabilidade"),
    ("si A puede llegar a B por una cadena de influencias",
     "se A pode chegar a B por uma cadeia de influências"),

    # Encadenamiento de módulos
    ("Los siete módulos se pueden encadenar — el resultado de uno",
     "Os sete módulos podem ser encadeados — o resultado de um"),
    ("alimenta al siguiente. Una ruta natural:",
     "alimenta o seguinte. Uma rota natural:"),
    ("Una vez identificadas las variables motrices,",
     "Uma vez identificadas as variáveis motoras,"),
    ("el módulo de evaluación de política diseña el plan formal",
     "o módulo de avaliação de política desenha o plano formal"),
    ("para medir si las intervenciones efectivamente movieron el sistema",
     "para medir se as intervenções efetivamente moveram o sistema"),
    ("con poder sobre esas variables — sus alianzas, sus conflictos",
     "com poder sobre essas variáveis — suas alianças, seus conflitos"),
    ("y dónde está el juego político real.",
     "e onde está o jogo político real."),
    ("El módulo de problema público te lleva por:",
     "O módulo de problema público leva você por:"),
    ("enunciado · evidencia · alternativas · criterios · comparación",
     "enunciado · evidência · alternativas · critérios · comparação"),
    ("Es el paso 0 del lab.",
     "É o passo 0 do lab."),
    ("Combina el trabajo que ya hayas avanzado en los seis módulos",
     "Combina o trabalho que você já tenha avançado nos seis módulos"),
    ("en un solo memo CONPES.",
     "em um único memorando CONPES."),
    ("Si solo completaste algunos, el informe lo refleja",
     "Se você só completou alguns, o relatório reflete isso"),

    # Recursos / fundamentos
    ("Repositorios oficiales colombianos e internacionales",
     "Repositórios oficiais colombianos e internacionais"),
    ("que vale la pena tener a mano cuando trabajas con cualquiera de los módulos",
     "que vale a pena ter à mão ao trabalhar com qualquer dos módulos"),
    ("Precargar datos públicos de Colombia",
     "Pré-carregar dados públicos da Colômbia"),
    ("como punto de partida",
     "como ponto de partida"),
    ("La literatura completa que usamos para iterar los módulos",
     "A literatura completa que usamos para iterar os módulos"),
    ("vive en nuestro corpus interno y se actualiza con cada nueva publicación",
     "vive em nosso corpus interno e é atualizada a cada nova publicação"),

    # Operacionales / cloud
    ("Tu trabajo se guarda localmente en este navegador y no se pierde.",
     "Seu trabalho é salvo localmente neste navegador e não se perde."),
    ("Para compartir un proyecto con tu equipo",
     "Para compartilhar um projeto com sua equipe"),
    ("o acceder desde otro dispositivo",
     "ou acessar de outro dispositivo"),
    ("Solo los colaboradores invitados pueden ver y editar este proyecto.",
     "Apenas os colaboradores convidados podem ver e editar este projeto."),
    ("Les llegará un correo con un enlace para aceptar y entrar.",
     "Eles receberão um e-mail com um link para aceitar e entrar."),
    ("Todo el cálculo se hace en tu navegador.",
     "Todo o cálculo é feito no seu navegador."),
    ("Si guardas en la nube, solo viajan los nombres de variables",
     "Se você salvar na nuvem, só trafegam os nomes das variáveis"),
    ("y las calificaciones",
     "e as classificações"),
    ("Tienes un análisis estructural sin terminar.",
     "Você tem uma análise estrutural inacabada."),
    ("Retomar análisis estructural",
     "Retomar análise estrutural"),
    ("Cargar o abrir proyecto",
     "Carregar ou abrir projeto"),

    # Frases conceptuales medias
    ("La calidad del análisis",
     "A qualidade da análise"),
    ("para llevarlo a comité.",
     "para levar ao comitê."),
    ("Para que el resultado sea robusto",
     "Para que o resultado seja robusto"),
    ("aplicamos tres técnicas distintas sobre la misma información que tú das",
     "aplicamos três técnicas diferentes sobre a mesma informação que você fornece"),
    ("Te mostramos cifras públicas oficiales",
     "Mostramos números públicos oficiais"),
    ("Colombia, departamento o municipio según lo que elijas",
     "Colômbia, departamento ou município conforme você escolher"),
    ("Sprint E habilitó",
     "O Sprint E habilitou"),
    ("a nivel nacional, departamental y municipal.",
     "em nível nacional, departamental e municipal."),

    # Misc UI strings
    ("Una muestra de cómo transformo datos públicos en tableros",
     "Uma amostra de como transformo dados públicos em painéis"),
    ("que facilitan la toma de decisiones.",
     "que facilitam a tomada de decisões."),
    ("Pequeños cambios ahí pueden disparar el sistema entero",
     "Pequenas mudanças aí podem disparar o sistema inteiro"),
    ("Además te damos un ranking ordenado",
     "Além disso, damos um ranking ordenado"),
    ("y puedes descargar todo",
     "e você pode baixar tudo"),

    # JS-embedded UI phrases
    ("Tu análisis ha sido guardado", "Sua análise foi salva"),
    ("Análisis guardado", "Análise salva"),
    ("Guardado en la nube", "Salvo na nuvem"),
    ("Cargar análisis", "Carregar análise"),
    ("Nuevo análisis", "Nova análise"),
    ("Confirmar eliminación", "Confirmar exclusão"),
    ("¿Estás seguro?", "Tem certeza?"),
    ("Esta acción no se puede deshacer", "Esta ação não pode ser desfeita"),
    ("Selecciona un proyecto", "Selecione um projeto"),
    ("Carga un proyecto existente", "Carregue um projeto existente"),
    ("Crear nuevo análisis", "Criar nova análise"),
    ("Sin proyectos guardados", "Sem projetos salvos"),
    ("calculando recomendación", "calculando recomendação"),
    ("¿Cómo lo calculamos?", "Como calculamos?"),
    ("¿En qué se basa?", "Em que se baseia?"),
    ("¿Cómo funciona?", "Como funciona?"),

    # Stage labels (chunks)
    ("Bienvenida", "Boas-vindas"),
    ("Definir variables", "Definir variáveis"),
    ("Captura de matriz", "Captura da matriz"),
    ("Análisis estructural", "Análise estrutural"),
    ("Resultados del análisis", "Resultados da análise"),
    ("Política pública", "Política pública"),
    ("Laboratorio de Políticas", "Laboratório de Políticas"),
    ("Recursos &amp; Datos", "Recursos &amp; Dados"),
    ("Recursos y Datos", "Recursos e Dados"),
    ("Análisis de actores", "Análise de atores"),
    ("Evaluación de política", "Avaliação de política"),
    ("Alternativas de política", "Alternativas de política"),
    ("Análisis de Impacto Normativo", "Análise de Impacto Normativo"),
    ("Escenarios prospectivos", "Cenários prospectivos"),
    ("Mi informe del lab", "Meu relatório do lab"),
    ("Informe combinado", "Relatório combinado"),
    ("Proyectos", "Projetos"),
    ("Modo día", "Modo dia"),
    ("Modo noche", "Modo noite"),

    # ─── Frases que no se pueden traducir palabra-a-palabra ──────────────
    ("entre sí", "entre si"),  # reflexivo, no es "sim" (afirmativo)
    ("a sí misma", "a si mesma"),
    ("a sí mismo", "a si mesmo"),
    ("a sí mismas", "a si mesmas"),
    ("a sí mismos", "a si mesmos"),
    ("para sí", "para si"),
    ("consigo mismo", "consigo mesmo"),
    ("consigo misma", "consigo mesma"),
    ("Sí lo es.", "Sim, é."),
    ("Sí es", "Sim, é"),
    ("¿Sí?", "Sim?"),

    # Otros chunks frecuentes
    ("Te ayuda a", "Ajuda você a"),
    ("Te ayudamos a", "Ajudamos você a"),
    ("Te mostramos", "Mostramos"),
    ("Te lleva", "Leva você"),
    ("Te toma", "Toma você"),
    ("Te da", "Dá a você"),
    ("verlas", "vê-las"),
    ("describirla", "descrevê-la"),
    ("discutirla", "discuti-la"),
    ("compararlas", "compará-las"),
    ("hacerlas", "fazê-las"),
    ("levarlo", "levá-lo"),
    ("llevarlo", "levá-lo"),
    ("llevarla", "levá-la"),

    # Sustantivos / verbos frecuentes restantes que aparecen mucho
    ("muchas", "muitas"),
    ("muchos", "muitos"),
    ("mucho", "muito"),
    ("mucha", "muita"),
    ("Mucho", "Muito"),
    ("Mucha", "Muita"),
    ("Muchas", "Muitas"),
    ("Muchos", "Muitos"),
    ("conectan", "conectam"),
    ("conectar", "conectar"),
    ("conecta", "conecta"),
    ("dinero", "dinheiro"),
    ("Dinero", "Dinheiro"),
    ("débil", "fraca"),
    ("Débil", "Fraca"),
    ("fuerte", "forte"),
    ("Fuerte", "Forte"),
    ("media", "média"),
    ("Media", "Média"),
    ("simples", "simples"),
    ("simple", "simples"),
    ("Simple", "Simples"),
    ("fórmulas", "fórmulas"),
    # ese/esa/esos/esas → movidos a WORDS (word-bounded): como substring
    # corrompían palabras ("pesado"→"pessado", "presente"→"pressente").
    ("redacta", "redige"),
    ("redactar", "redigir"),
    ("redactamos", "redigimos"),
    ("ambigüedades", "ambiguidades"),
    ("solapamientos", "sobreposições"),
    ("solapa", "sobrepõe"),
    ("solapan", "sobrepõem"),
    ("solaparse", "sobrepor-se"),
    ("enmarcar", "enquadrar"),
    ("enmarcar el problema", "enquadrar o problema"),
    ("probar", "testar"),
    ("probarla", "testá-la"),
    ("probarlas", "testá-las"),
    ("probarlo", "testá-lo"),
    ("probarlos", "testá-los"),
    ("conviene", "convém"),
    ("Conviene", "Convém"),
    ("se conviene", "convém"),
    ("reducir", "reduzir"),
    ("Reducir", "Reduzir"),
    ("reduce", "reduz"),
    ("reduces", "reduz"),
    ("reducen", "reduzem"),
    ("redujo", "reduziu"),
    ("redujimos", "reduzimos"),
    ("redujeron", "reduziram"),
    ("verlas todas juntas", "vê-las todas juntas"),
    ("entender", "entender"),
    ("entenderla", "entendê-la"),
    ("entenderlo", "entendê-lo"),
    ("entendido", "entendido"),
    ("entendemos", "entendemos"),
    ("entiende", "entende"),
    ("entienden", "entendem"),
    ("entiendes", "entende"),
    ("se entiende", "se entende"),
    ("se entienden", "se entendem"),

    # "consultoras" como palabra suelta no quedó cubierta antes
    ("consultoras", "consultorias"),
    ("Consultoras", "Consultorias"),

    # Cuantificadores que quedaron como "muchas, muitas, etc."
    ("Muchos", "Muitos"),
    ("Muchas", "Muitas"),

    # Frases comunes
    ("tan bien", "tão bem"),
    ("o que tan bien", "quão bem"),
    ("o que tão bem", "quão bem"),
    ("casi en su totalidad", "quase totalmente"),
    ("para llevarlo a comitê", "para levá-lo ao comitê"),
    ("para levarlo a comitê", "para levá-lo ao comitê"),
    ("dependen ella de as demás", "ela depende das demais"),
    ("dependen ella de las demás", "ela depende das demais"),
    ("uma sobre a otra", "uma sobre a outra"),
    ("uma sobre la otra", "uma sobre a outra"),
    ("o que necesites", "o que precisar"),
    ("le mostra", "mostra"),
    ("Le mostra", "Mostra"),
    ("le dice", "diz"),

    # Específicos del Lab
    ("anclaje regulatorio colombiano",
     "ancoragem regulatória colombiana"),
    ("cierra o ciclo",
     "fecha o ciclo"),
    ("cierra el ciclo",
     "fecha o ciclo"),
    ("a leitura interpretativa de os resultados de as três",
     "a leitura interpretativa dos resultados das três"),
    ("de las tres", "das três"),
    ("de os módulos", "dos módulos"),
    ("de las tres lentes", "das três lentes"),
    ("de las dos técnicas", "das duas técnicas"),
    ("se conoces", "se você conhece"),
    ("Se conoces", "Se você conhece"),
    ("conoces", "conhece"),
    ("conocemos", "conhecemos"),
    ("conocer", "conhecer"),
    ("conoce", "conhece"),
    ("conocido", "conhecido"),
    ("ti mismo", "você mesmo"),
    ("a ti", "a você"),
    ("por ti", "por você"),
    ("contigo mismo", "com você mesmo"),

    # Lote 4 — palabras puntuales
    ("Siete", "Sete"),
    ("siete", "sete"),
    ("Cuatro", "Quatro"),
    ("cuatro", "quatro"),
    ("Cinco", "Cinco"),
    ("cinco", "cinco"),
    ("Seis", "Seis"),
    ("seis", "seis"),
    ("Ocho", "Oito"),
    ("ocho", "oito"),
    ("Nueve", "Nove"),
    ("nueve", "nove"),
    ("Diez", "Dez"),
    ("diez", "dez"),
    ("plausibles", "plausíveis"),
    ("plausible", "plausível"),
    ("pocas", "poucas"),
    ("pocos", "poucos"),
    ("poco", "pouco"),
    ("poca", "pouca"),
    ("Poco", "Pouco"),
    ("calificas", "classifica"),
    ("calificar", "classificar"),
    ("califica", "classifica"),
    ("calificamos", "classificamos"),
    ("influyen", "influenciam"),
    ("influye", "influencia"),
    ("influir", "influenciar"),
    ("homicidios", "homicídios"),
    ("Homicidios", "Homicídios"),
    ("homicidio", "homicídio"),
    ("usarla", "usá-la"),
    ("usarlo", "usá-lo"),
    ("usarlos", "usá-los"),
    ("usarlas", "usá-las"),
    ("descargarla", "baixá-la"),
    ("descargarlo", "baixá-lo"),
    ("descargarlos", "baixá-los"),
    ("compartirla", "compartilhá-la"),
    ("compartirlo", "compartilhá-lo"),
    ("Va a ", "Vai "),
    (" va a ", " vai "),
    (" vamos a ", " vamos "),

    # Pequeñas estructurales
    ("o que tão bem", "quão bem"),
    ("se as nomeia", "se as nomeia"),
    ("uma sobre la otra", "uma sobre a outra"),
    ("uma sobre a otra", "uma sobre a outra"),
    ("la otra", "a outra"),
    # otra/otras/otro/otros → movidos a WORDS (word-bounded): como substring
    # corrompían "nosotros"→"nosoutros", "vosotros", etc.
    ("dices", "diz"),
    ("decimos", "dizemos"),
    ("Estamos", "Estamos"),
    ("estamos", "estamos"),
    ("hablas", "fala"),
    ("hablamos", "falamos"),
    ("hablan", "falam"),
    ("habla", "fala"),
    ("ahí", "aí"),
    ("Ahí", "Aí"),
    ("le ayuda", "ajuda"),
    ("le da", "dá"),
    ("le dice", "diz"),
    ("le permite", "permite"),
    ("le mostra", "mostra"),
    ("Le mostra", "Mostra"),
    ("lo faz", "faz"),
    ("lo é", "é"),
    ("lo hace", "faz"),
    ("lo hacemos", "fazemos"),
    ("lo necesario", "o necessário"),
    ("ni de", "nem de"),
    ("ni el", "nem o"),
    ("Para que", "Para que"),

    # Otros
    ("usa", "usa"),
    ("usás", "usa"),
    ("usamos", "usamos"),
    ("usar", "usar"),
    ("usaste", "usou"),
    ("usado", "usado"),
    ("usaron", "usaram"),

    # Domain tiles
    ("Seguridad urbana", "Segurança urbana"),
    ("Salud pública", "Saúde pública"),
    ("Educación", "Educação"),
    ("Economía y empleo", "Economia e emprego"),
    ("Ambiente y clima", "Meio ambiente e clima"),
    ("Movilidad", "Mobilidade"),
    ("Gobernanza", "Governança"),
    ("Agricultura", "Agricultura"),
    ("Vivienda", "Habitação"),
    ("Energía", "Energia"),
    ("Cultura", "Cultura"),
    ("Tecnología", "Tecnologia"),
    ("Ciencia", "Ciência"),
    ("Justicia", "Justiça"),
    ("Asuntos exteriores", "Relações exteriores"),
    ("Sin dominio definido", "Sem domínio definido"),

    # Buttons / labels frecuentes (≥6 chars)
    ("Iniciar sesión", "Entrar"),
    ("Registrarse", "Cadastrar"),
    ("Volver", "Voltar"),
    ("Empezar módulo", "Começar módulo"),
    ("Ver resultados", "Ver resultados"),
    ("Empezar", "Começar"),
    ("Empecemos", "Vamos começar"),
    ("Cargar proyecto", "Carregar projeto"),
    ("Guardar en la nube", "Salvar na nuvem"),
    ("Compartir", "Compartilhar"),
    ("Mis proyectos", "Meus projetos"),
    ("Nuevo proyecto", "Novo projeto"),
    ("Plantillas", "Modelos"),
    ("Plantilla", "Modelo"),
    ("Aceptar", "Aceitar"),
    ("Cancelar", "Cancelar"),
    ("Guardar", "Salvar"),
    ("Cerrar", "Fechar"),
    ("Continuar", "Continuar"),
    ("Siguiente", "Próximo"),
    ("Anterior", "Anterior"),
    ("Descargar", "Baixar"),
    ("Imprimir", "Imprimir"),
    ("Exportar", "Exportar"),
    ("Importar", "Importar"),
    ("Eliminar", "Excluir"),
    ("Editar", "Editar"),
    ("Agregar", "Adicionar"),
    ("Resultados", "Resultados"),
    ("Inicio", "Início"),

    # ─── Lote PT v2 · términos técnicos protegidos (no traducir) ─────────────
    ("no-regret", "no-regret"), ("no-regrets", "no-regrets"),
    ("NO-REGRET", "NO-REGRET"), ("what-if", "what-if"),
    ("What-if", "What-if"), ("trade-off", "trade-off"),
    ("trade-offs", "trade-offs"),

    # ─── Lote PT v2 · negaciones (corren antes que las WORDS) ────────────────
    # Más largas primero para que ganen la coincidencia.
    ("no se puede", "não se pode"), ("No se puede", "Não se pode"),
    ("no se pueden", "não se podem"),
    ("no tienes", "não tem"), ("no tiene", "não tem"), ("no tienen", "não têm"),
    ("no quieres", "não quer"), ("no necesitas", "não precisa"),
    ("no sabes", "não sabe"), ("no sabe", "não sabe"),
    ("no pueden", "não podem"), ("no puede", "não pode"),
    ("no hay", "não há"), ("No hay", "Não há"),
    ("no son", "não são"), ("No son", "Não são"),
    ("no es", "não é"), ("No es", "Não é"),
    ("no las", "não as"), ("no los", "não os"),
    ("no lo", "não o"), ("no la", "não a"),
    ("no se", "não se"), ("No se", "Não se"),
    ("aún no", "ainda não"), ("Aún no", "Ainda não"),
    ("todavía no", "ainda não"), ("Todavía no", "Ainda não"),
    ("ya no", "já não"), ("Ya no", "Já não"),

    # ─── Lote PT v2 · qué/cuál con preposición (orden de palabras) ───────────
    ("en qué", "em que"), ("En qué", "Em que"),
    ("de qué", "de que"), ("De qué", "De que"),
    ("a qué", "a que"), ("A qué", "A que"),
    ("sobre qué", "sobre o que"), ("Sobre qué", "Sobre o que"),
    ("lo que", "o que"), ("Lo que", "O que"),
    ("qué tanto", "quanto"), ("Qué tanto", "Quanto"),
    ("qué tan", "quão"), ("Qué tan", "Quão"),
    ("qué tipo", "que tipo"), ("Qué tipo", "Que tipo"),
    ("para qué", "para que"), ("Para qué", "Para que"),
    ("por qué", "por que"), ("Por qué", "Por que"),

    # ─── Lote PT v2 · "va/vas/van a + inf" → "vai/vão + inf" ──────────────────
    (" vas a ", " vai "), (" van a ", " vão "), (" voy a ", " vou "),

    # ─── Lote PT v2 · giros frecuentes ───────────────────────────────────────
    ("Te recomendamos", "Recomendamos"), ("te recomendamos", "recomendamos"),
    ("Ten en cuenta", "Tenha em conta"), ("ten en cuenta", "tenha em conta"),
    ("a la vez", "ao mesmo tempo"),

    # ─── Lote PT v2 · en/de + demostrativo → contracción portuguesa ──────────
    ("en estos", "nestes"), ("En estos", "Nestes"),
    ("en estas", "nestas"), ("En estas", "Nestas"),
    ("en este", "neste"), ("En este", "Neste"),
    ("en esta", "nesta"), ("En esta", "Nesta"),
    ("en esos", "nesses"), ("en esas", "nessas"),
    ("en ese", "nesse"), ("en esa", "nessa"),
    ("de estos", "destes"), ("de estas", "destas"),
    ("de este", "deste"), ("de esta", "desta"),
    ("de esos", "desses"), ("de esas", "dessas"),
    ("de ese", "desse"), ("de esa", "dessa"),
]

# ─── WORDS (palabras sueltas, word-boundary regex) ────────────────────────
# Ordenadas: específicas primero, genéricas después.
# Para evitar romper palabras, todas las entradas usan \b…\b.
WORDS = [
    # Articles (definidos)
    (r"\bel\b", "o"),
    (r"\bEl\b", "O"),
    (r"\bla\b", "a"),
    (r"\bLa\b", "A"),
    (r"\blos\b", "os"),
    (r"\bLos\b", "Os"),
    (r"\blas\b", "as"),
    (r"\bLas\b", "As"),
    # Articles (indefinidos)
    (r"\bun\b", "um"),
    (r"\bUn\b", "Um"),
    (r"\buna\b", "uma"),
    (r"\bUna\b", "Uma"),
    (r"\bunos\b", "uns"),
    (r"\bunas\b", "umas"),
    # Preposiciones / contracciones
    (r"\bdel\b", "do"),
    (r"\bDel\b", "Do"),
    (r"\bal\b", "ao"),
    (r"\bAl\b", "Ao"),
    (r"\ben\b", "em"),
    (r"\bEn\b", "Em"),
    (r"\bcon\b", "com"),
    (r"\bCon\b", "Com"),
    (r"\bsin\b", "sem"),
    (r"\bSin\b", "Sem"),
    (r"\bhasta\b", "até"),
    (r"\bHasta\b", "Até"),
    (r"\bhacia\b", "para"),
    (r"\bHacia\b", "Para"),
    (r"\bbajo\b", "sob"),
    (r"\bsegún\b", "segundo"),
    (r"\bSegún\b", "Segundo"),
    # Conjunciones / conectores
    (r"\by\b", "e"),
    (r"\bY\b", "E"),
    (r"\bya\b", "já"),
    (r"\bYa\b", "Já"),
    (r"\bo\b", "ou"),
    (r"\bO\b", "Ou"),
    (r"\bpero\b", "mas"),
    (r"\bPero\b", "Mas"),
    (r"\bsino\b", "mas sim"),
    (r"\bsi\b", "se"),
    (r"\bSi\b", "Se"),
    # OJO: "sí" en español puede ser "sim" (afirmativo) o "si" (entre sí).
    # No traducimos en bulk; agregamos casos puntuales como PHRASES.
    (r"\bporque\b", "porque"),
    (r"\bcomo\b", "como"),
    (r"\bCómo\b", "Como"),
    (r"\bcómo\b", "como"),
    (r"\baunque\b", "embora"),
    (r"\bAunque\b", "Embora"),
    (r"\bmientras\b", "enquanto"),
    (r"\bMientras\b", "Enquanto"),
    (r"\bcuando\b", "quando"),
    (r"\bCuando\b", "Quando"),
    # Pronombres / demostrativos
    (r"\beso\b", "isso"),
    (r"\bEso\b", "Isso"),
    (r"\besto\b", "isto"),
    (r"\bEsto\b", "Isto"),
    (r"\bestos\b", "estes"),
    (r"\bEstos\b", "Estes"),
    (r"\bestas\b", "estas"),
    (r"\bEstas\b", "Estas"),
    (r"\baquel\b", "aquele"),
    (r"\baquellos\b", "aqueles"),
    (r"\bnosotros\b", "nós"),
    (r"\bNosotros\b", "Nós"),
    (r"\bvosotros\b", "vocês"),
    (r"\bustedes\b", "vocês"),
    (r"\bUstedes\b", "Vocês"),
    (r"\bellos\b", "eles"),
    (r"\bEllos\b", "Eles"),
    (r"\bellas\b", "elas"),
    (r"\bEllas\b", "Elas"),
    # Posesivos
    (r"\bnuestro\b", "nosso"),
    (r"\bnuestra\b", "nossa"),
    (r"\bnuestros\b", "nossos"),
    (r"\bnuestras\b", "nossas"),
    (r"\bvuestro\b", "seu"),
    (r"\btu\b", "seu"),
    (r"\bTu\b", "Seu"),
    (r"\btus\b", "seus"),
    (r"\bTus\b", "Seus"),
    (r"\bti\b", "você"),
    (r"\bcontigo\b", "com você"),
    # Verbos ser / estar / haber / tener (presente/pasado más frecuentes)
    (r"\bes\b", "é"),
    (r"\bEs\b", "É"),
    (r"\bson\b", "são"),
    (r"\bSon\b", "São"),
    (r"\bera\b", "era"),
    (r"\beran\b", "eram"),
    (r"\bfue\b", "foi"),
    (r"\bfueron\b", "foram"),
    (r"\bestán\b", "estão"),
    (r"\bEstán\b", "Estão"),
    (r"\bestaba\b", "estava"),
    (r"\bestaban\b", "estavam"),
    (r"\btiene\b", "tem"),
    (r"\bTiene\b", "Tem"),
    (r"\btienes\b", "tem"),
    (r"\bTienes\b", "Tem"),
    (r"\btienen\b", "têm"),
    (r"\bTienen\b", "Têm"),
    (r"\bEntiende\b", "Entende"),
    (r"\bentiende\b", "entende"),
    (r"\bEntiendes\b", "Entende"),
    (r"\bentiendes\b", "entende"),
    (r"\bEntienden\b", "Entendem"),
    (r"\bentienden\b", "entendem"),
    (r"\bConozco\b", "Conheço"),
    (r"\bconozco\b", "conheço"),
    (r"\bConoces\b", "Conhece"),
    (r"\btener\b", "ter"),
    (r"\btenido\b", "tido"),
    (r"\bhay\b", "há"),
    (r"\bHay\b", "Há"),
    (r"\bha\b", "tem"),
    (r"\bhan\b", "têm"),
    # Otros verbos comunes
    (r"\bhacer\b", "fazer"),
    (r"\bhace\b", "faz"),
    (r"\bhacen\b", "fazem"),
    (r"\bhecho\b", "feito"),
    (r"\bhicimos\b", "fizemos"),
    (r"\bdecir\b", "dizer"),
    (r"\bdice\b", "diz"),
    (r"\bdicen\b", "dizem"),
    (r"\bllevar\b", "levar"),
    (r"\bllevarlo\b", "levá-lo"),
    (r"\bdejar\b", "deixar"),
    (r"\bdeja\b", "deixa"),
    (r"\bdejan\b", "deixam"),
    (r"\bqueda\b", "fica"),
    (r"\bquedan\b", "ficam"),
    (r"\bquedar\b", "ficar"),
    (r"\bquedó\b", "ficou"),
    (r"\bpuede\b", "pode"),
    (r"\bPuede\b", "Pode"),
    (r"\bpueden\b", "podem"),
    (r"\bpueda\b", "possa"),
    (r"\bpuedas\b", "possa"),
    (r"\bvas\b", "vai"),
    (r"\bvan\b", "vão"),
    (r"\bvienes\b", "vem"),
    (r"\bviene\b", "vem"),
    (r"\bvienen\b", "vêm"),
    (r"\bvenir\b", "vir"),
    (r"\bllamamos\b", "chamamos"),
    (r"\bllaman\b", "chamam"),
    (r"\bllamado\b", "chamado"),
    (r"\bllamada\b", "chamada"),
    (r"\bllamar\b", "chamar"),
    (r"\bdescribir\b", "descrever"),
    (r"\bdescribiendo\b", "descrevendo"),
    (r"\bsabes\b", "sabe"),
    (r"\bsabe\b", "sabe"),
    (r"\bsaber\b", "saber"),
    (r"\bnecesitas\b", "precisa"),
    (r"\bnecesita\b", "precisa"),
    (r"\bnecesitan\b", "precisam"),
    (r"\bnecesitamos\b", "precisamos"),
    (r"\bnecesitar\b", "precisar"),
    (r"\bnecesario\b", "necessário"),
    (r"\bcompletar\b", "completar"),
    (r"\bcompletaste\b", "completou"),
    (r"\bcompletado\b", "completado"),
    (r"\bmuestra\b", "mostra"),
    (r"\bmostrar\b", "mostrar"),
    (r"\bmostramos\b", "mostramos"),
    (r"\bmoverlas\b", "movê-las"),
    (r"\bmueve\b", "move"),
    (r"\bmueven\b", "movem"),
    (r"\bmovieron\b", "moveram"),
    (r"\bmotrices\b", "motoras"),
    (r"\bmotriz\b", "motora"),
    (r"\babrir\b", "abrir"),
    (r"\babre\b", "abre"),
    (r"\babrir\b", "abrir"),
    (r"\bdescargar\b", "baixar"),
    (r"\bdescarga\b", "download"),
    (r"\benviar\b", "enviar"),
    (r"\benvía\b", "envia"),
    (r"\brecibir\b", "receber"),
    (r"\brecibe\b", "recebe"),
    (r"\brecibimos\b", "recebemos"),
    (r"\bañadir\b", "adicionar"),
    (r"\bañade\b", "adiciona"),
    (r"\bañadido\b", "adicionado"),
    (r"\bquitar\b", "remover"),
    (r"\bquita\b", "remove"),
    (r"\bquitamos\b", "removemos"),
    (r"\bencontrar\b", "encontrar"),
    (r"\bencuentra\b", "encontra"),
    (r"\bencuentras\b", "encontra"),
    (r"\bencuentran\b", "encontram"),
    (r"\bbuscar\b", "buscar"),
    (r"\bbusca\b", "busca"),
    (r"\bbuscas\b", "busca"),
    (r"\babre\b", "abre"),
    (r"\baplicó\b", "aplicou"),
    (r"\baplicar\b", "aplicar"),
    (r"\baplicamos\b", "aplicamos"),
    (r"\baplica\b", "aplica"),
    (r"\bcalcula\b", "calcula"),
    (r"\bcalcular\b", "calcular"),
    (r"\bcalculo\b", "cálculo"),
    (r"\bcálculo\b", "cálculo"),
    (r"\bperder\b", "perder"),
    (r"\bpierde\b", "perde"),
    (r"\bpierden\b", "perdem"),
    (r"\bganar\b", "ganhar"),
    (r"\bgana\b", "ganha"),
    (r"\bgrabar\b", "gravar"),
    (r"\bgrabar\b", "gravar"),
    (r"\bguardar\b", "salvar"),
    (r"\bguarda\b", "salva"),
    (r"\bguardas\b", "salva"),
    (r"\bguardamos\b", "salvamos"),
    (r"\bguardado\b", "salvo"),
    (r"\bcrear\b", "criar"),
    (r"\bcrea\b", "cria"),
    (r"\bcreamos\b", "criamos"),
    (r"\bcompartir\b", "compartilhar"),
    (r"\bcomparte\b", "compartilha"),
    (r"\bcompartimos\b", "compartilhamos"),
    (r"\bacceder\b", "acessar"),
    (r"\baccede\b", "acessa"),
    (r"\bacceso\b", "acesso"),
    (r"\bregistrarse\b", "cadastrar"),
    (r"\binicia\b", "inicia"),
    (r"\biniciar\b", "iniciar"),
    (r"\bsesión\b", "sessão"),
    (r"\bSesión\b", "Sessão"),
    # Adverbios / cuantificadores
    (r"\btambién\b", "também"),
    (r"\bTambién\b", "Também"),
    (r"\bahora\b", "agora"),
    (r"\bAhora\b", "Agora"),
    (r"\bentonces\b", "então"),
    (r"\bEntonces\b", "Então"),
    (r"\bademás\b", "além disso"),
    (r"\bAdemás\b", "Além disso"),
    (r"\bantes\b", "antes"),
    (r"\bdespués\b", "depois"),
    (r"\bDespués\b", "Depois"),
    (r"\bluego\b", "depois"),
    (r"\btan\b", "tão"),
    (r"\bmuy\b", "muito"),
    (r"\bMuy\b", "Muito"),
    (r"\bmás\b", "mais"),
    (r"\bMás\b", "Mais"),
    (r"\bmejor\b", "melhor"),
    (r"\bMejor\b", "Melhor"),
    (r"\bmayor\b", "maior"),
    (r"\bMayor\b", "Maior"),
    (r"\bmenor\b", "menor"),
    (r"\bMenor\b", "Menor"),
    (r"\bsiempre\b", "sempre"),
    (r"\btodavía\b", "ainda"),
    (r"\baún\b", "ainda"),
    (r"\bAún\b", "Ainda"),
    (r"\bbien\b", "bem"),
    (r"\bBien\b", "Bem"),
    (r"\bbueno\b", "bom"),
    (r"\bBueno\b", "Bom"),
    (r"\bbuena\b", "boa"),
    (r"\bBuena\b", "Boa"),
    (r"\bsolo\b", "apenas"),
    (r"\bSolo\b", "Apenas"),
    (r"\bsólo\b", "apenas"),
    (r"\bSólo\b", "Apenas"),
    (r"\baquí\b", "aqui"),
    (r"\bahí\b", "aí"),
    (r"\ballí\b", "ali"),
    # Question words
    (r"\bQué\b", "O que"),
    (r"\bqué\b", "o que"),
    (r"\bCuándo\b", "Quando"),
    (r"\bcuándo\b", "quando"),
    (r"\bCuánto\b", "Quanto"),
    (r"\bcuánto\b", "quanto"),
    (r"\bCuántos\b", "Quantos"),
    (r"\bcuántos\b", "quantos"),
    (r"\bCuánta\b", "Quanta"),
    (r"\bcuánta\b", "quanta"),
    (r"\bQuién\b", "Quem"),
    (r"\bquién\b", "quem"),
    (r"\bDónde\b", "Onde"),
    (r"\bdónde\b", "onde"),
    (r"\bPor qué\b", "Por que"),
    (r"\bpor qué\b", "por que"),
    # Cierre
    (r"\bsalir\b", "sair"),
    (r"\bSalir\b", "Sair"),
    (r"\bAtrás\b", "Voltar"),
    (r"\bAceptar\b", "Aceitar"),
    (r"\bEnviar\b", "Enviar"),
    (r"\bEditar\b", "Editar"),
    (r"\bAgregar\b", "Adicionar"),
    (r"\bRecibir\b", "Receber"),
    (r"\bnuevo\b", "novo"),
    (r"\bNuevo\b", "Novo"),
    (r"\bnueva\b", "nova"),
    (r"\bNueva\b", "Nova"),
    (r"\bnuevos\b", "novos"),
    (r"\bNuevos\b", "Novos"),
    (r"\bnuevas\b", "novas"),
    (r"\bNuevas\b", "Novas"),

    # Términos PP / lab
    (r"\bComité\b", "Comitê"),
    (r"\bcomité\b", "comitê"),
    (r"\bplaneación\b", "planejamento"),
    (r"\bseguridad\b", "segurança"),
    (r"\beducación\b", "educação"),
    (r"\bmovilidad\b", "mobilidade"),
    (r"\bcomplejo\b", "complexo"),
    (r"\bcomplejos\b", "complexos"),
    (r"\bcompleja\b", "complexa"),
    (r"\bcomplejas\b", "complexas"),

    # Verbos / sustantivos comunes
    (r"\bherramienta\b", "ferramenta"),
    (r"\bherramientas\b", "ferramentas"),
    (r"\bincertidumbre\b", "incerteza"),
    (r"\bIncertidumbre\b", "Incerteza"),
    (r"\bincertidumbres\b", "incertezas"),
    (r"\bconocimiento\b", "conhecimento"),
    (r"\binformación\b", "informação"),
    (r"\bsugerencia\b", "sugestão"),
    (r"\bsugerencias\b", "sugestões"),
    (r"\brecomendación\b", "recomendação"),
    (r"\brecomendaciones\b", "recomendações"),
    (r"\bevaluación\b", "avaliação"),
    (r"\bEvaluación\b", "Avaliação"),
    (r"\bcalificación\b", "classificação"),
    (r"\bCalificación\b", "Classificação"),
    (r"\bcalificaciones\b", "classificações"),
    (r"\bdecisión\b", "decisão"),
    (r"\bdecisiones\b", "decisões"),
    (r"\bestadística\b", "estatística"),
    (r"\bdesafío\b", "desafio"),
    (r"\bobjetivo\b", "objetivo"),
    (r"\bobjetivos\b", "objetivos"),
    (r"\bescenario\b", "cenário"),
    (r"\bescenarios\b", "cenários"),
    (r"\bEscenario\b", "Cenário"),
    (r"\bEscenarios\b", "Cenários"),
    (r"\briesgo\b", "risco"),
    (r"\briesgos\b", "riscos"),
    (r"\bRiesgo\b", "Risco"),
    (r"\bRiesgos\b", "Riscos"),
    (r"\boportunidad\b", "oportunidade"),
    (r"\boportunidades\b", "oportunidades"),
    (r"\bhallazgo\b", "achado"),
    (r"\bhallazgos\b", "achados"),
    (r"\bpiezas\b", "peças"),
    (r"\bpieza\b", "peça"),
    (r"\bpropósito\b", "propósito"),
    (r"\bequipo\b", "equipe"),
    (r"\bequipos\b", "equipes"),
    (r"\bdesempeño\b", "desempenho"),
    (r"\bdisponible\b", "disponível"),
    (r"\bdisponibles\b", "disponíveis"),
    (r"\bavanzado\b", "avançado"),
    (r"\bavanzados\b", "avançados"),
    (r"\bavanzar\b", "avançar"),
    (r"\bavanzada\b", "avançada"),
    (r"\bmetodología\b", "metodologia"),
    (r"\bMetodología\b", "Metodologia"),

    # Conjunciones / preps
    (r"\by\b", "e"),
    (r"\bya\b", "já"),
    (r"\bsí\b", "sim"),
    (r"\bo\b", "ou"),
    (r"\bpero\b", "mas"),
    (r"\bdesde\b", "desde"),
    (r"\bes decir\b", "ou seja"),
    (r"\bsin embargo\b", "no entanto"),
    (r"\baunque\b", "embora"),
    (r"\btambién\b", "também"),
    (r"\bahora\b", "agora"),
    (r"\bentonces\b", "então"),
    (r"\bademás\b", "além disso"),
    (r"\bhacer\b", "fazer"),
    (r"\bantes\b", "antes"),
    (r"\bdespués\b", "depois"),
    (r"\bluego\b", "depois"),
    (r"\btu\b", "seu"),
    (r"\bTu\b", "Seu"),
    (r"\btus\b", "seus"),
    (r"\bTus\b", "Seus"),
    (r"\bcontigo\b", "com você"),
    (r"\bti\b", "você"),
    (r"\bsolo\b", "apenas"),
    (r"\bSolo\b", "Apenas"),

    # Question words
    (r"\bCómo\b", "Como"),
    (r"\bcómo\b", "como"),
    (r"\bQué\b", "O que"),
    (r"\bqué\b", "o que"),
    (r"\bCuándo\b", "Quando"),
    (r"\bcuándo\b", "quando"),
    (r"\bCuánto\b", "Quanto"),
    (r"\bcuánto\b", "quanto"),
    (r"\bQuién\b", "Quem"),
    (r"\bquién\b", "quem"),
    (r"\bDónde\b", "Onde"),
    (r"\bdónde\b", "onde"),

    # ─── Lote 2 — palabras frecuentes restantes ──────────────────────────
    (r"\binvertir\b", "investir"),
    (r"\binvierte\b", "investe"),
    (r"\bpresupuesto\b", "orçamento"),
    (r"\brespuesta\b", "resposta"),
    (r"\bRespuesta\b", "Resposta"),
    (r"\brespuestas\b", "respostas"),
    (r"\bnecesidad\b", "necessidade"),
    (r"\bNecesidad\b", "Necessidade"),
    (r"\bnecesidades\b", "necessidades"),
    (r"\bdescribiendo\b", "descrevendo"),
    (r"\binterpretativa\b", "interpretativa"),
    (r"\binterpretación\b", "interpretação"),
    (r"\btres\b", "três"),
    (r"\bTres\b", "Três"),
    (r"\bdos\b", "dois"),
    (r"\bDos\b", "Dois"),
    (r"\blectura\b", "leitura"),
    (r"\blecturas\b", "leituras"),
    (r"\beliges\b", "escolhe"),
    (r"\belijas\b", "escolha"),
    (r"\belijan\b", "escolham"),
    (r"\belegir\b", "escolher"),
    (r"\belegido\b", "escolhido"),
    (r"\belegida\b", "escolhida"),
    (r"\belegidos\b", "escolhidos"),
    (r"\belegidas\b", "escolhidas"),
    (r"\bescoger\b", "escolher"),
    (r"\bescoge\b", "escolhe"),
    (r"\bescogiste\b", "escolheu"),
    (r"\bcalidad\b", "qualidade"),
    (r"\bCalidad\b", "Qualidade"),
    (r"\bamplio\b", "amplo"),
    (r"\bamplia\b", "ampla"),
    (r"\btuya\b", "sua"),
    (r"\btuyo\b", "seu"),
    (r"\bcabría\b", "caberia"),
    (r"\bcualquier\b", "qualquer"),
    (r"\bcualquiera\b", "qualquer"),
    (r"\bpuedo\b", "posso"),
    (r"\bponer\b", "colocar"),
    (r"\bponen\b", "colocam"),
    (r"\bpones\b", "coloca"),
    (r"\bponemos\b", "colocamos"),
    (r"\bprimero\b", "primeiro"),
    (r"\bprimera\b", "primeira"),
    (r"\bprimer\b", "primeiro"),
    (r"\btercero\b", "terceiro"),
    (r"\btercera\b", "terceira"),
    (r"\bpregunta\b", "pergunta"),
    (r"\bpreguntas\b", "perguntas"),
    (r"\bPregunta\b", "Pergunta"),
    (r"\bPreguntas\b", "Perguntas"),
    (r"\bpreguntar\b", "perguntar"),
    (r"\bdemás\b", "demais"),
    (r"\bdependen\b", "dependem"),
    (r"\bdependiendo\b", "dependendo"),
    (r"\balcaldía\b", "prefeitura"),
    (r"\bAlcaldía\b", "Prefeitura"),
    (r"\balcaldías\b", "prefeituras"),
    (r"\bAlcaldías\b", "Prefeituras"),
    (r"\balumbrado\b", "iluminação"),
    (r"\bhurto\b", "roubo"),
    (r"\bpresencia\b", "presença"),
    (r"\bpolicía\b", "polícia"),
    (r"\bquieres\b", "quer"),
    (r"\bquiere\b", "quer"),
    (r"\bquieren\b", "querem"),
    (r"\bintervenciones\b", "intervenções"),
    (r"\bIntervenciones\b", "Intervenções"),
    (r"\bintervención\b", "intervenção"),
    (r"\bIntervención\b", "Intervenção"),
    (r"\bdistintas\b", "diferentes"),
    (r"\bdistintos\b", "diferentes"),
    (r"\bdistinta\b", "diferente"),
    (r"\bdistinto\b", "diferente"),
    (r"\bproceso\b", "processo"),
    (r"\bprocesos\b", "processos"),
    (r"\bentregable\b", "entregável"),
    (r"\bentregables\b", "entregáveis"),
    (r"\bcomplementarias\b", "complementares"),
    (r"\bcomplementaria\b", "complementar"),
    (r"\bcomplementarios\b", "complementares"),
    (r"\bcomplementario\b", "complementar"),
    (r"\bvariable\b", "variável"),
    (r"\bvariables\b", "variáveis"),
    (r"\bVariable\b", "Variável"),
    (r"\bVariables\b", "Variáveis"),
    (r"\bactor\b", "ator"),
    (r"\bactores\b", "atores"),
    (r"\bActor\b", "Ator"),
    (r"\bActores\b", "Atores"),
    (r"\bopciones\b", "opções"),
    (r"\bOpciones\b", "Opções"),
    (r"\bopción\b", "opção"),
    (r"\bOpción\b", "Opção"),
    (r"\bmensurables\b", "mensuráveis"),
    (r"\bmensurable\b", "mensurável"),
    (r"\bmedibles\b", "mensuráveis"),
    (r"\bmedible\b", "mensurável"),
    (r"\bproyecto\b", "projeto"),
    (r"\bProyecto\b", "Projeto"),
    (r"\bproyectos\b", "projetos"),
    (r"\bProyectos\b", "Projetos"),
    (r"\bdiseño\b", "desenho"),
    (r"\bdiseñar\b", "desenhar"),
    (r"\bdiseña\b", "desenha"),
    (r"\bdiseñan\b", "desenham"),
    (r"\bdiseñado\b", "desenhado"),
    (r"\bdiseñada\b", "desenhada"),
    (r"\bplan\b", "plano"),
    (r"\bplanes\b", "planos"),
    (r"\bcambios\b", "mudanças"),
    (r"\bcambio\b", "mudança"),
    (r"\bCambio\b", "Mudança"),
    (r"\bCambios\b", "Mudanças"),
    (r"\bteoría\b", "teoria"),
    (r"\bTeoría\b", "Teoria"),
    (r"\bteorías\b", "teorias"),
    (r"\bteórico\b", "teórico"),
    (r"\bteórica\b", "teórica"),
    (r"\bselector\b", "seletor"),
    (r"\bmétodo\b", "método"),
    (r"\bMétodo\b", "Método"),
    (r"\bmétodos\b", "métodos"),
    (r"\bMétodos\b", "Métodos"),
    (r"\bsintético\b", "sintético"),
    (r"\bsintética\b", "sintética"),
    (r"\binforme\b", "relatório"),
    (r"\binformes\b", "relatórios"),
    (r"\bInforme\b", "Relatório"),
    (r"\bInformes\b", "Relatórios"),
    (r"\banálisis\b", "análise"),
    (r"\bAnálisis\b", "Análise"),
    (r"\bestructural\b", "estrutural"),
    (r"\bEstructural\b", "Estrutural"),
    (r"\bestructurales\b", "estruturais"),
    (r"\bdiagnóstico\b", "diagnóstico"),
    (r"\bDiagnóstico\b", "Diagnóstico"),
    (r"\bdiagnósticos\b", "diagnósticos"),
    (r"\bestratégico\b", "estratégico"),
    (r"\bEstratégico\b", "Estratégico"),
    (r"\bestratégica\b", "estratégica"),
    (r"\bEstratégica\b", "Estratégica"),
    (r"\bestrategia\b", "estratégia"),
    (r"\bEstrategia\b", "Estratégia"),
    (r"\bestrategias\b", "estratégias"),
    (r"\bplanificación\b", "planejamento"),
    (r"\bplaneación\b", "planejamento"),
    (r"\bPlaneación\b", "Planejamento"),
    (r"\bdepartamento\b", "departamento"),
    (r"\bdepartamentos\b", "departamentos"),
    (r"\bmunicipio\b", "município"),
    (r"\bmunicipios\b", "municípios"),
    (r"\bMunicipio\b", "Município"),
    (r"\bMunicipios\b", "Municípios"),
    (r"\bsectorial\b", "setorial"),
    (r"\bSectorial\b", "Setorial"),
    # Verbos pp comunes
    (r"\bayudar\b", "ajudar"),
    (r"\bayudamos\b", "ajudamos"),
    (r"\bayuda\b", "ajuda"),
    (r"\bAyuda\b", "Ajuda"),
    (r"\bayudará\b", "ajudará"),
    (r"\bcrearás\b", "criará"),
    (r"\bcreaste\b", "criou"),
    (r"\bcreada\b", "criada"),
    (r"\bcreado\b", "criado"),
    (r"\benseñar\b", "ensinar"),
    (r"\benseñamos\b", "ensinamos"),
    (r"\bsugerir\b", "sugerir"),
    (r"\bsugerimos\b", "sugerimos"),
    (r"\bsugiere\b", "sugere"),
    (r"\bsugieren\b", "sugerem"),
    (r"\bllenar\b", "preencher"),
    (r"\bllena\b", "preenche"),
    (r"\bllenamos\b", "preenchemos"),
    (r"\bdescribirla\b", "descrevê-la"),
    (r"\bdescribir\b", "descrever"),
    (r"\bdescriben\b", "descrevem"),
    (r"\bdescribe\b", "descreve"),
    (r"\baplicado\b", "aplicado"),
    (r"\bdemasiado\b", "demais"),
    (r"\bdemasiada\b", "demais"),
    (r"\bsuficiente\b", "suficiente"),
    (r"\bsuficientes\b", "suficientes"),
    # Otros sustantivos
    (r"\bvalor\b", "valor"),
    (r"\bvalores\b", "valores"),
    (r"\bnúmero\b", "número"),
    (r"\bnúmeros\b", "números"),
    (r"\bNúmero\b", "Número"),
    (r"\bNúmeros\b", "Números"),
    (r"\bnombre\b", "nome"),
    (r"\bnombres\b", "nomes"),
    (r"\bNombre\b", "Nome"),
    (r"\bnombrar\b", "nomear"),
    (r"\bnombramos\b", "nomeamos"),
    (r"\bnombres\b", "nomes"),
    (r"\bnombras\b", "nomeia"),
    (r"\bayudará\b", "ajudará"),
    (r"\bpaso\b", "passo"),
    (r"\bPaso\b", "Passo"),
    (r"\bpasos\b", "passos"),
    (r"\betapa\b", "etapa"),
    (r"\bEtapa\b", "Etapa"),
    (r"\betapas\b", "etapas"),
    (r"\bcantidad\b", "quantidade"),
    (r"\bcantidades\b", "quantidades"),
    (r"\bCantidad\b", "Quantidade"),
    (r"\baspecto\b", "aspecto"),
    (r"\baspectos\b", "aspectos"),
    (r"\bfondo\b", "fundo"),
    (r"\bsalud\b", "saúde"),
    (r"\bSalud\b", "Saúde"),
    (r"\beducación\b", "educação"),
    (r"\bEducación\b", "Educação"),
    (r"\bbúsqueda\b", "busca"),
    (r"\bcontenido\b", "conteúdo"),
    (r"\bcontenidos\b", "conteúdos"),
    (r"\bcomunidad\b", "comunidade"),
    (r"\bcomunidades\b", "comunidades"),
    (r"\bbarrio\b", "bairro"),
    (r"\bbarrios\b", "bairros"),
    (r"\bvecino\b", "vizinho"),
    (r"\bvecinos\b", "vizinhos"),
    (r"\bvecindario\b", "vizinhança"),
    (r"\bcaso\b", "caso"),
    (r"\bcasos\b", "casos"),
    (r"\bejemplo\b", "exemplo"),
    (r"\bejemplos\b", "exemplos"),
    (r"\bEjemplo\b", "Exemplo"),

    # ─── Lote PT v2 · words adicionales (corren tras las PHRASES) ────────────
    (r"\bno\b", "não"), (r"\bNo\b", "Não"),
    (r"\bCuál\b", "Qual"), (r"\bcuál\b", "qual"),
    (r"\bCuáles\b", "Quais"), (r"\bcuáles\b", "quais"),
    (r"\bestás\b", "está"), (r"\bEstás\b", "Está"),
    (r"\bestoy\b", "estou"), (r"\bEstoy\b", "Estou"),
    (r"\besté\b", "esteja"), (r"\bestés\b", "esteja"),
    (r"\beres\b", "é"), (r"\bEres\b", "É"),
    (r"\bsoy\b", "sou"), (r"\bSoy\b", "Sou"),
    (r"\bhoy\b", "hoje"), (r"\bHoy\b", "Hoje"),
    (r"\btrabajar\b", "trabalhar"), (r"\btrabaja\b", "trabalha"),
    (r"\btrabajan\b", "trabalham"), (r"\btrabajamos\b", "trabalhamos"),
    (r"\bevaluar\b", "avaliar"), (r"\bevalúa\b", "avalia"),
    (r"\bevalúan\b", "avaliam"), (r"\bevaluará\b", "avaliará"),
    (r"\bevaluamos\b", "avaliamos"), (r"\bevaluado\b", "avaliado"),
    (r"\bejercicio\b", "exercício"), (r"\bEjercicio\b", "Exercício"),
    (r"\borganización\b", "organização"), (r"\bOrganización\b", "Organização"),
    (r"\borganizaciones\b", "organizações"),
    (r"\bdominio\b", "domínio"), (r"\bDominio\b", "Domínio"), (r"\bdominios\b", "domínios"),
    (r"\bpalanca\b", "alavanca"), (r"\bpalancas\b", "alavancas"),
    (r"\bPalanca\b", "Alavanca"), (r"\bPalancas\b", "Alavancas"),
    (r"\bpasa\b", "passa"), (r"\bpasan\b", "passam"), (r"\bpasar\b", "passar"),
    (r"\bpase\b", "passe"), (r"\bpasó\b", "passou"),
    (r"\bcambia\b", "muda"), (r"\bcambian\b", "mudam"), (r"\bcambiar\b", "mudar"),
    (r"\bcambió\b", "mudou"), (r"\bcambie\b", "mude"),
    (r"\benmarcado\b", "enquadrado"), (r"\benmarcada\b", "enquadrada"),
    (r"\benmarca\b", "enquadra"),
    (r"\bdeshacer\b", "desfazer"),
    (r"\bapoyo\b", "apoio"), (r"\bApoyo\b", "Apoio"),
    (r"\bapoya\b", "apoia"), (r"\bapoyan\b", "apoiam"), (r"\bapoyar\b", "apoiar"),
    (r"\bmensaje\b", "mensagem"), (r"\bmensajes\b", "mensagens"),
    (r"\bMensaje\b", "Mensagem"), (r"\bMensajes\b", "Mensagens"),
    (r"\baudiencia\b", "audiência"), (r"\baudiencias\b", "audiências"),
    (r"\bAudiencia\b", "Audiência"), (r"\bAudiencias\b", "Audiências"),
    (r"\bcanales\b", "canais"), (r"\bCanales\b", "Canais"),
    (r"\bcelda\b", "célula"), (r"\bceldas\b", "células"),
    (r"\bcuadrante\b", "quadrante"), (r"\bcuadrantes\b", "quadrantes"),
    (r"\bumbral\b", "limiar"), (r"\bUmbral\b", "Limiar"),
    (r"\bcolumna\b", "coluna"), (r"\bcolumnas\b", "colunas"),
    (r"\bflecha\b", "seta"), (r"\bflechas\b", "setas"),
    (r"\bpantalla\b", "tela"), (r"\bPantalla\b", "Tela"),
    (r"\bborrador\b", "rascunho"), (r"\bBorrador\b", "Rascunho"),
    (r"\bencuadre\b", "enquadramento"), (r"\bEncuadre\b", "Enquadramento"),
    (r"\bvocero\b", "porta-voz"), (r"\bvoceros\b", "porta-vozes"),
    (r"\bsiguiente\b", "seguinte"), (r"\bSiguiente\b", "Seguinte"),
    (r"\bpendiente\b", "pendente"), (r"\bPendiente\b", "Pendente"),
    (r"\bpendientes\b", "pendentes"), (r"\bPendientes\b", "Pendentes"),
    (r"\btrabajas\b", "trabalha"),
    (r"\brecomienda\b", "recomenda"), (r"\brecomiendan\b", "recomendam"),
    (r"\brecomendará\b", "recomendará"),

    # demostrativos ese/esa (word-bounded; antes eran substring y corrompían palabras)
    (r"\bese\b", "esse"), (r"\bEse\b", "Esse"),
    (r"\besa\b", "essa"), (r"\bEsa\b", "Essa"),
    (r"\besos\b", "esses"), (r"\bEsos\b", "Esses"),
    (r"\besas\b", "essas"), (r"\bEsas\b", "Essas"),
    # otra/otro (word-bounded; antes substring corrompía nosotros/vosotros)
    (r"\botra\b", "outra"), (r"\bOtra\b", "Outra"),
    (r"\botras\b", "outras"), (r"\bOtras\b", "Outras"),
    (r"\botro\b", "outro"), (r"\bOtro\b", "Outro"),
    (r"\botros\b", "outros"), (r"\bOtros\b", "Outros"),
    (r"\bnosotras\b", "nós"), (r"\bvosotras\b", "vocês"),

    # vocabulario frecuente que quedaba en español
    (r"\bplantilla\b", "modelo"), (r"\bplantillas\b", "modelos"),
    (r"\blenguaje\b", "linguagem"), (r"\bLenguaje\b", "Linguagem"),
    (r"\badecuado\b", "adequado"), (r"\badecuada\b", "adequada"),
    (r"\bAdecuado\b", "Adequado"), (r"\bAdecuada\b", "Adequada"),
    (r"\badecuados\b", "adequados"), (r"\badecuadas\b", "adequadas"),
    (r"\bdonde\b", "onde"), (r"\bDonde\b", "Onde"),
    (r"\bproduce\b", "produz"), (r"\bproducen\b", "produzem"),
    (r"\bproducir\b", "produzir"), (r"\bprodujo\b", "produziu"),
    (r"\bcombinación\b", "combinação"), (r"\bCombinación\b", "Combinação"),
    (r"\bcombinaciones\b", "combinações"), (r"\bCombinaciones\b", "Combinações"),
    (r"\bcuán\b", "quão"), (r"\bCuán\b", "Quão"),
    (r"\bEscoge\b", "Escolha"),
    (r"\bpodrás\b", "poderá"), (r"\bpodrá\b", "poderá"), (r"\bpodrán\b", "poderão"),
    (r"\bpodremos\b", "poderemos"), (r"\bpodría\b", "poderia"), (r"\bpodrían\b", "poderiam"),
    (r"\bquizás\b", "talvez"), (r"\bQuizás\b", "Talvez"),
    (r"\btú\b", "você"), (r"\bTú\b", "Você"),
    (r"\btrabajo\b", "trabalho"), (r"\bTrabajo\b", "Trabalho"),
    (r"\bnube\b", "nuvem"), (r"\bNube\b", "Nuvem"),
    (r"\bcuenta\b", "conta"), (r"\bCuenta\b", "Conta"), (r"\bcuentas\b", "contas"),
    (r"\binvitados\b", "convidados"), (r"\binvitado\b", "convidado"),
    (r"\binvitada\b", "convidada"), (r"\binvitadas\b", "convidadas"),
    (r"\binvitar\b", "convidar"), (r"\binvita\b", "convida"),
    (r"\bcorreo\b", "e-mail"), (r"\bCorreo\b", "E-mail"), (r"\bcorreos\b", "e-mails"),
    (r"\benlace\b", "link"), (r"\bEnlace\b", "Link"), (r"\benlaces\b", "links"),
    (r"\bposición\b", "posição"), (r"\bPosición\b", "Posição"),
    (r"\bposiciones\b", "posições"), (r"\bPosiciones\b", "Posições"),
    (r"\bhipótesis\b", "hipótese"), (r"\bHipótesis\b", "Hipótese"),
    (r"\bexperto\b", "especialista"), (r"\bexpertos\b", "especialistas"),
    (r"\bExperto\b", "Especialista"), (r"\bexperta\b", "especialista"),
    (r"\bLectura\b", "Leitura"),
    (r"\bcomposición\b", "composição"), (r"\bComposición\b", "Composição"),
    (r"\bguardarlo\b", "salvá-lo"), (r"\bguardarla\b", "salvá-la"),
    (r"\bguardarlos\b", "salvá-los"), (r"\bguardarlas\b", "salvá-las"),
    (r"\bagrega\b", "adiciona"), (r"\bagregar\b", "adicionar"),
    (r"\bagregue\b", "adicione"), (r"\bagregas\b", "adiciona"),
    (r"\bsegún\b", "segundo"), (r"\bSegún\b", "Segundo"),
    (r"\bademás\b", "além disso"),
]

_PHRASE_BUFFER = []  # contiene los segmentos traducidos por PHRASES

def apply_phrases(text):
    """Reemplaza frases largas y guarda cada salida en un buffer marcado
    con \x03{i}\x04 para que apply_words no las re-traduzca."""
    for src_str, dst_str in PHRASES:
        while src_str in text:
            idx = len(_PHRASE_BUFFER)
            _PHRASE_BUFFER.append(dst_str)
            text = text.replace(src_str, f"\x03{idx}\x04", 1)
    return text

def restore_phrases(text):
    """Reinyecta los segmentos del buffer en el texto."""
    def _sub(m):
        return _PHRASE_BUFFER[int(m.group(1))]
    return re.sub(r"\x03(\d+)\x04", _sub, text)

# ─── Contracciones PT (em+art, de+art, a+art, por+art) ────────────────────
# El traductor produce "em o / de a / a la→a a" tras la pasada de palabras;
# aquí se recombinan en las contracciones correctas del portugués.
_CONTRACTIONS = [
    (r"\bem os\b", "nos"), (r"\bEm os\b", "Nos"),
    (r"\bem as\b", "nas"), (r"\bEm as\b", "Nas"),
    (r"\bem o\b", "no"),   (r"\bEm o\b", "No"),
    (r"\bem a\b", "na"),   (r"\bEm a\b", "Na"),
    (r"\bem um\b", "num"), (r"\bem uma\b", "numa"),
    (r"\bde os\b", "dos"), (r"\bDe os\b", "Dos"),
    (r"\bde as\b", "das"), (r"\bDe as\b", "Das"),
    (r"\bde o\b", "do"),   (r"\bDe o\b", "Do"),
    (r"\bde a\b", "da"),   (r"\bDe a\b", "Da"),
    (r"\ba os\b", "aos"),  (r"\bA os\b", "Aos"),
    (r"\ba as\b", "às"),   (r"\bA as\b", "Às"),
    (r"\ba o\b", "ao"),    (r"\bA o\b", "Ao"),
    (r"\ba a\b", "à"),     (r"\bA a\b", "À"),
    (r"\bpor os\b", "pelos"), (r"\bpor as\b", "pelas"),
    (r"\bpor o\b", "pelo"),   (r"\bPor o\b", "Pelo"),
    (r"\bpor a\b", "pela"),   (r"\bPor a\b", "Pela"),
]
_CONTRACTIONS_C = [(re.compile(p), r) for p, r in _CONTRACTIONS]

def contract(text):
    for rx, rep in _CONTRACTIONS_C:
        text = rx.sub(rep, text)
    return text

# ─── Single-pass word translation (evita cadenas tipo el → o → ou) ────────
# Construimos un mapa palabra-completa → reemplazo y un regex que matchea
# CUALQUIERA de las claves. Una sola pasada garantiza que cada palabra
# se traduce una vez según su forma de entrada en español.
_WORD_MAP = {}
for _pat, _dst in WORDS:
    # _pat es del estilo r"\bfoo\b"; extraemos "foo".
    m = re.fullmatch(r"\\b(.+)\\b", _pat)
    if not m:
        continue
    key = m.group(1)
    # Si ya está en el mapa con otro valor, mantenemos el primero (orden).
    if key not in _WORD_MAP:
        _WORD_MAP[key] = _dst

# Ordenar claves por longitud descendente para que el regex prefiera la
# coincidencia más larga (e.g. "más" sobre "ma").
_KEYS_SORTED = sorted(_WORD_MAP.keys(), key=lambda k: -len(k))
# Escapamos cada clave por seguridad regex y construimos alternancia.
_WORD_RE = re.compile(
    r"(?<![\wÀ-ſ])(" + "|".join(re.escape(k) for k in _KEYS_SORTED) + r")(?![\wÀ-ſ])"
)

def apply_words(text):
    return _WORD_RE.sub(lambda m: _WORD_MAP[m.group(1)], text)

def _translate_text_run(s):
    new = apply_phrases(s)
    new = apply_words(new)
    new = restore_phrases(new)
    new = contract(new)
    return new

def _translate_template(m):
    """Traduce el texto literal de un template literal `...`, dejando intactas
    las interpolaciones ${...}. Si la interpolación tiene llaves anidadas, no
    arriesga y devuelve el literal sin tocar."""
    inner = m.group(1)
    interps = []
    def _ip(mm):
        interps.append(mm.group(0))
        return f"\x02{len(interps)-1}\x02"
    tmp = re.sub(r"\$\{[^{}]*\}", _ip, inner)
    if "${" in tmp or "}" in tmp:          # interpolación con llaves anidadas
        return m.group(0)
    if not re.search(r"[A-Za-zÁÉÍÓÚáéíóúñÑ]", tmp):
        return m.group(0)
    new = _translate_text_run(tmp)
    new = re.sub(r"\x02(\d+)\x02", lambda mm: interps[int(mm.group(1))], new)
    return "`" + new + "`"

def _translate_script(script_text):
    """Translate string-literals + template literals inside JS that look like UI."""
    # 1) Template literals (backticks) — texto literal, preservando ${...}.
    script_text = re.sub(r"`([^`]*)`", _translate_template, script_text, flags=re.DOTALL)
    # 2) String literals '...' "..."
    def _replace_str(m):
        quote = m.group(1)
        content = m.group(2)
        if not re.search(r"[a-zA-Záéíóúñ]", content):
            return m.group(0)
        if len(content) < 4:
            return m.group(0)
        # Skip if no spaces AND no Spanish-specific chars (probably ID/path)
        if " " not in content and not re.search(r"[áéíóúñÑ¿¡]", content):
            return m.group(0)
        return quote + _translate_text_run(content) + quote
    out = re.sub(
        r"(['\"])((?:\\.|(?!\1).)*)\1",
        _replace_str,
        script_text,
    )
    return out

def rewrite_crosslinks(text):
    """Reescribe enlaces ES→PT entre módulos del Lab, preservando #anchor/?query."""
    for es, pt in MODULES.items():
        text = re.sub(r"(?<![\w./-])" + re.escape(es) + r"(?![\w])", pt, text)
    return text

def translate_file(src_path, dst_path):
    _PHRASE_BUFFER.clear()
    src = src_path.read_text(encoding="utf-8")

    # lang attr (cualquier variante de <html ... lang="es" ...>)
    src = re.sub(r'(<html[^>]*\blang=")es(")', r'\1pt-BR\2', src)

    # Proteger <style>, <script> y atributos URL (href/src/action).
    styles = []
    src = re.sub(r"<style[^>]*>.*?</style>",
                 lambda m: (styles.append(m.group(0)) or f"\x00STYLE{len(styles)-1}\x00"),
                 src, flags=re.DOTALL)
    scripts = []
    src = re.sub(r"<script[^>]*>.*?</script>",
                 lambda m: (scripts.append(m.group(0)) or f"\x00SCRIPT{len(scripts)-1}\x00"),
                 src, flags=re.DOTALL)
    attrs = []
    src = re.sub(r'\b(?:href|src|action)\s*=\s*(["\']).*?\1',
                 lambda m: (attrs.append(m.group(0)) or f"\x00ATTR{len(attrs)-1}\x00"),
                 src, flags=re.DOTALL)

    # Traducir HTML visible: frases → palabras → restaurar frases → contraer.
    src = apply_phrases(src)
    src = apply_words(src)
    src = restore_phrases(src)
    src = contract(src)

    # Restaurar atributos URL (sin traducir, con cross-links ES→PT reescritos).
    for i, a in enumerate(attrs):
        src = src.replace(f"\x00ATTR{i}\x00", rewrite_crosslinks(a))
    # Restaurar <style> intacto.
    for i, st in enumerate(styles):
        src = src.replace(f"\x00STYLE{i}\x00", st)
    # Restaurar <script>: traducir string-literals + reescribir cross-links.
    for i, sc in enumerate(scripts):
        src = src.replace(f"\x00SCRIPT{i}\x00", rewrite_crosslinks(_translate_script(sc)))

    # Quitar signos de apertura del español (no existen en portugués).
    src = src.replace("¿", "").replace("¡", "")

    dst_path.write_text(src, encoding="utf-8")
    return len(src)

def main():
    import sys
    only = sys.argv[1] if len(sys.argv) > 1 else None
    for es, pt in MODULES.items():
        if only and only not in (es, pt):
            continue
        src_path = ROOT / es
        if not src_path.exists():
            print(f"⚠  falta {es} — salto")
            continue
        n = translate_file(src_path, ROOT / pt)
        out = (ROOT / pt).read_text(encoding="utf-8")
        resid = out.count("¿") + out.count("¡")
        print(f"OK · {es:28s} → {pt:30s} {n:>9,} chars · ¿¡ residual: {resid}")

if __name__ == "__main__":
    main()
